# Generated by Django 4.2 on 2023-04-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappone', '0002_employee_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
