# Generated by Django 4.2 on 2023-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myappone', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('emplname', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('joiningdate', models.DateField(null=True)),
                ('Esalary', models.IntegerField()),
                ('Egmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
