# Generated by Django 4.2 on 2023-04-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappone', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='Egmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='Esalary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='empid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='empname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
